### ISSUE TITLE
Volume mapping values for auth.allow with multiple ips

### ISSUE THREAD

**Issue by tenajsystems** [voxpupuli/puppet-gluster#165]
Hi,

I keep getting the error below when I try to set multiple ips for "auth.allow" for a volume and I can't seem to figure out why or what I might be doing wrong.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, (<unknown>): mapping values are not allowed here at line 2 column 25 at /etc/puppetlabs/code/environments/test/modules/gluster/manifests/volume.pp:276:21 at /etc/puppetlabs/code/environments/test/manifests/classes/test/gluster/glusterd_volume.pp:52 on node example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Could someone help me figureout what I might be doing wrong?

**Comment by tsemeijn** [comment]
Setting multiple IP addresses in auth.allow works fine for me. Removing them though results in the following error:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, (<unknown>): mapping values are not allowed here`

It looks like parseyaml() fails with commas in the value of auth.allow thus it not being able to process any changes to a present value of auth.allow containing commas. Commas in values is not something YAML seems to handle.

**Comment by tsemeijn** [comment]
Nope @tenajsystems unfortunately not. For now I do not use auth.allow as it is not a production environment. Would love to see it work though.

**Comment by gdnico** [comment]
Hello,

If i reboot my server before run puppet, puppet run and apply the configuration. The muliple IPs is OK if i don't separe it with a space. 
But  the second run failed with the same errors :
root@xxxxxx ~]# puppet agent -t --environment work --server xxxxxx
Info: Using configured environment 'work'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for xxxxxx
Info: Applying configuration version '1527838022'
Notice: /Stage[main]/Profile::Gluster_server/Gluster::Peer[xxxxxxxx]/Exec[gluster peer probe xxxxxxxxxxl]/returns: executed successfully
Notice: /Stage[main]/Profile::Gluster_server/Profile::Gluster::Volume[volume_talend_esb_app]/Gluster::Volume[talend_esb_app]/Gluster::Volume::Option[talend_esb_app:auth.allow]/Exec
[gluster option talend_esb_app auth.allow 10.127.228.56,10.127.228.57]/returns: executed successfully
Notice: Applied catalog in 16.32 seconds
[root@xxxxx ~]# puppet agent -t --environment work --server xxxxxxx
Info: Using configured environment 'work'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error whil
e evaluating a Function Call, (<unknown>): mapping values are not allowed here at line 2 column 26 at /etc/puppetlabs/code/environments/work/modules-r10k/gluster/manifests/volume.p
p:276:21 at /etc/puppetlabs/code/environments/work/modules/profile/manifests/gluster/volume.pp:35 on node xxxxxxx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Between the two runs i don't change anything in my code. If i reboot my server i can run puppet without error
In my opinion the problem is in the fact
