### ISSUE TITLE
 Volume creation has race condition with fact gluster_volume_list

### ISSUE THREAD

**Issue by tux-o-matic** [voxpupuli/puppet-gluster#23]
My attempt to create a volume with two nodes seems stuck at the volume creation.
```shell
Evaluation Error: Error while evaluating a Function Call, function 'split' called with mis-matched arguments
```
Then points to volume.pp line 105. The split function there depends on the Fact 'gluster_volume_list' except that one is undef at this stage cause it is only populated if the cluster pool has a volume.

Or am I missing something?

**Comment by skpy** [comment]
Which version of Puppet are you using?

I just tried with open source Puppet 4.3.0 and can confirm that I get the same error.  I suspect a change to the split function has occurred somewhere since when we published this module, and now.  Maybe [PUP-4463](https://tickets.puppetlabs.com/browse/PUP-4463)?

**Comment by tux-o-matic** [comment]
Puppet 4.2 and stdlib 4.5.1.
I'll be testing a change to handle missing the undef Fact in those versions and then create a PR.

**Comment by tux-o-matic** [comment]
Issue with the 'gluster_volume_list' Fact and the split() function is now by passed in #24.
In my case I no longer get errors but volume creation doesn't happen. Peer status seems correct on both nodes.

**Comment by tux-o-matic** [comment]
With #24 merged, this is resolved.
