### ISSUE TITLE
Support commas in volume options

### ISSUE THREAD

**Issue by rauchrob** [voxpupuli/puppet-gluster#53]
Currently, volume options are collected as comma seperated list using the `gluster_volume_${title}_options` fact. However, some volume options may have values containing commas as well (for example, `nfs.rpc-auth-allow`).

In order to make this work, I see two approaches:
- Use another seperating character in the list of volume options provided by the `gluster_volume_${title}_options` fact (this should ideally be a character, which would never ever occur in volume option names and values). For example, `gluster_volume_${title}_options` could be something like `option1: 'value1', option2: 'value2,value3'`
- Use Facter arrays/hashes (which are, AFAIK, guaranteed to be available only for Puppet >= 4.0)

**Comment by skpy** [comment]
String parsing stinks.  I'd be perfectly happy with structured facts. That would require a major version increase in this module's version to denote a breaking change according to semver.

**Comment by rauchrob** [comment]
In our environment we are still locked to Puppet 3.x because Foreman and its friends do not yet support Puppet 4.x. I think many people out there are also still using Puppet 3. What about using the `parseyaml` function of the `puppetlabs/stdlib` module for parsing the volume options from the `gluster_volume_${title}_options` fact?

**Comment by tenajsystems** [comment]
@skpy and @rauchrob, Did any of you figure out how to get this to work? I am currently having the same issue with ```auth.allow``` which also takes comma separated list but when I try to set multiple ips, I get the error below:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, (<unknown>): mapping values are not allowed here at line 2 column 25 at /etc/puppetlabs/code/environments/test/modules/gluster/manifests/volume.pp:276:21 at /etc/puppetlabs/code/environments/test/manifests/classes/test/gluster/glusterd_volume.pp:52 on node example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by gdnico** [comment]
@skpy  @tenajsystems @rauchrob 
If i reboot my server before run puppet, puppet run and apply the configuration. The muliple IPs is OK if i don't separe it with a space.
But the second run failed with the same errors :
root@xxxxxx ~]# puppet agent -t --environment work --server xxxxxx
Info: Using configured environment 'work'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for xxxxxx
Info: Applying configuration version '1527838022'
Notice: /Stage[main]/Profile::Gluster_server/Gluster::Peer[xxxxxxxx]/Exec[gluster peer probe xxxxxxxxxxl]/returns: executed successfully
Notice: /Stage[main]/Profile::Gluster_server/Profile::Gluster::Volume[volume_talend_esb_app]/Gluster::Volume[talend_esb_app]/Gluster::Volume::Option[talend_esb_app:auth.allow]/Exec
[gluster option talend_esb_app auth.allow 10.127.228.56,10.127.228.57]/returns: executed successfully
Notice: Applied catalog in 16.32 seconds
[root@xxxxx ~]# puppet agent -t --environment work --server xxxxxxx
Info: Using configured environment 'work'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error whil
e evaluating a Function Call, (): mapping values are not allowed here at line 2 column 26 at /etc/puppetlabs/code/environments/work/modules-r10k/gluster/manifests/volume.p
p:276:21 at /etc/puppetlabs/code/environments/work/modules/profile/manifests/gluster/volume.pp:35 on node xxxxxxx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Between the two runs i don't change anything in my code. If i reboot my server i can run puppet without error

I do another test, if the glusterd service is down the puppet code is ok, if the service is up the problem appear

In my opinion the problem is in the fact
